spring:
  datasource:
    hikari:
      username: root
      password: root1234
      #      jdbc-url: jdbc:mariadb://localhost:3306/cine_square?characterEncoding=UTF-8&serverTimezone=UTC
      #      driver-class-name: org.mariadb.jdbc.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log4j2
      #      jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/cine_square?characterEncoding=utf8&serverTimezone=UTC
      # docker 배포
#      jdbc-url: jdbc:log4jdbc:mysql://172.17.0.2:3306/cine_square?characterEncoding=utf8&serverTimezone=UTC
    # mylocal
      jdbc-url: jdbc:log4jdbc:mysql://54.180.29.206:3306/cine_square?characterEncoding=utf8&serverTimezone=UTC

  mail:
    default:
      encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: dlwjdwns010@gmail.com
    password: vjij jria udpb psxf
    # password: piql nafp oznv bmjp
#    username: Ysoomin12@gmail.com
#    password: advfcdrfpknswgdy
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

server:
  port: 9096

# 로컬 환경에서만 설정
#logging:
#  config: classpath:log4j2.yml
#  level:
#    com:
#      zaxxer:
#        hikari: INFO
#    javax:
#      sql:
#        DataSource: OFF
#    jdbc:
#      audit: OFF
#      resultset: OFF
#      resultsettable: INFO
#      sqlonly: DEBUG
#      sqltiming: OFF
#    org:
#      hibernate:
#        SQL: DEBUG
#        type:
#          descriptor:
#            sql:
#              BasicBinder: TRACE

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cinesquare.cinesquare.vo
