spring:
  datasource:
    hikari:
      username: root
      password: root1234
#      jdbc-url: jdbc:mariadb://localhost:3306/cine_square?characterEncoding=UTF-8&serverTimezone=UTC
#      driver-class-name: org.mariadb.jdbc.Driver
      driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy # log4j2
      #         jdbc-url: jdbc:log4jdbc:mysql://localhost:3306/cine_square?characterEncoding=utf8&serverTimezone=UTC
      # docker 배포
      jdbc-url: jdbc:log4jdbc:mysql://172.17.0.2:3306/cine_square?characterEncoding=utf8&serverTimezone=UTC
    # mylocal
#      jdbc-url: jdbc:log4jdbc:mariadb://localhost:3306/cine_square?characterEncoding=UTF-8&serverTimezone=UTC


            #logging:
            #  config: classpath:log4j2.yml

  mail:
    default:
      encoding: UTF-8
    host: smtp.gmail.com
    port: 587
    username: Ysoomin12@gmail.com
    password: advfcdrfpknswgdy
    properties:
      mail:
        smtp:
          auth: true
          timeout: 5000
          starttls:
            enable: true

server:
  port: 9096

# MyBatis Configuration
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: cinesquare.cinesquare.vo
